// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHrV1GHs092VtW-MAT85Pv2E8E_1h-RqA',
    appId: '1:339019304895:web:f4adc67fae22ae32ee9b0a',
    messagingSenderId: '339019304895',
    projectId: 'tap-to-shop',
    authDomain: 'tap-to-shop.firebaseapp.com',
    storageBucket: 'tap-to-shop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT5r9wdXb47jYQlEZL0IrId_qhAkdZVKE',
    appId: '1:339019304895:android:71981710ef315140ee9b0a',
    messagingSenderId: '339019304895',
    projectId: 'tap-to-shop',
    storageBucket: 'tap-to-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RhR80-2lhY1C9C--gOYr4OI8NE4YTKU',
    appId: '1:339019304895:ios:cedbb6a39ee36407ee9b0a',
    messagingSenderId: '339019304895',
    projectId: 'tap-to-shop',
    storageBucket: 'tap-to-shop.firebasestorage.app',
    iosBundleId: 'com.example.shopapp',
  );
}
