import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shopapp/features/capture/screens/capture_screen.dart';
import 'package:shopapp/screens/home_screen.dart';
import 'package:shopapp/screens/login_screen.dart';
import 'package:shopapp/screens/profile_screen.dart';
import 'package:shopapp/screens/results_screen.dart';
import 'package:shopapp/core/widgets/auth_wrapper.dart'; // Import AuthWrapper

import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async { // Make main async
  WidgetsFlutterBinding.ensureInitialized(); // Ensure bindings are initialized
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Use generated options
  );

  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Tap-to-Shop',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const AuthWrapper(), // NEW: Use AuthWrapper to decide initial screen
      routes: {
        LoginScreen.routeName: (context) => const LoginScreen(),
        HomeScreen.routeName: (context) => const HomeScreen(),
        CaptureScreen.routeName: (context) => const CaptureScreen(),
        ProfileScreen.routeName: (context) => const ProfileScreen(),
        // ResultsScreen requires arguments, handle in onGenerateRoute or pass via arguments
        // ResultsScreen.routeName: (context) => ResultsScreen(sessionId: 'temp-id'),
      },
      // Optional: Handle routes not explicitly defined or routes with arguments
      onGenerateRoute: (settings) {
         if (settings.name == ResultsScreen.routeName) {
           final args = settings.arguments as String?; // Example: expecting sessionId as String
           if (args != null) {
             return MaterialPageRoute(
               builder: (context) => ResultsScreen(sessionId: args),
             );
           }
           // Handle case where arguments are missing or invalid
           return MaterialPageRoute(builder: (context) => const HomeScreen()); // Or an error screen
         }
         // Handle other potential routes or return null
         return null;
      }
    );
  }
}
